# Generated by Django 4.1.3 on 2022-11-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('MessageId', models.AutoField(primary_key=True, serialize=False)),
                ('MessageContent', models.CharField(max_length=500)),
                ('MessageName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=500)),
                ('Message', models.CharField(max_length=50)),
                ('DateOfRegistration', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
