# Generated by Django 3.2 on 2023-02-25 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientApi', '0003_remove_dialog_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
