# Generated by Django 3.2 on 2023-03-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientApi', '0005_alter_message_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentuser',
            name='street',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
