# Generated by Django 3.2 on 2023-03-08 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientApi', '0006_currentuser_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentuser',
            name='street',
        ),
    ]
