# Generated by Django 3.2 on 2023-03-13 20:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientApi', '0008_emptydialog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentUser',
            new_name='Profile',
        ),
    ]
