# Generated by Django 4.1.1 on 2022-11-27 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('myuser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.myuser')),
            ],
        ),
    ]
