# Generated by Django 3.2 on 2023-03-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20230311_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
