# Generated by Django 4.1.7 on 2023-03-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_addfuturetravel_addpasttravel_myprofile_follows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
