# Generated by Django 4.1.1 on 2022-11-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_myprofile_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
