# Generated by Django 4.1.7 on 2023-04-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_myprofile_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.RemoveField(
            model_name='myprofile',
            name='follows',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='country',
            field=models.CharField(default='Country', max_length=50),
        ),
    ]
