# Generated by Django 4.1.7 on 2023-04-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_delete_myuser_remove_myprofile_follows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfuturetravel',
            name='money_spent',
            field=models.CharField(choices=[('150', 150), ('150-300', 225), ('300-500', 400), ('500-1000', 750), ('1000-3000', 2000), ('3000+', 3500)], max_length=100),
        ),
        migrations.AlterField(
            model_name='addpasttravel',
            name='money_spent',
            field=models.CharField(choices=[('150', 150), ('150-300', 225), ('300-500', 400), ('500-1000', 750), ('1000-3000', 2000), ('3000+', 3500)], max_length=100),
        ),
    ]
