# Generated by Django 3.2 on 2023-03-18 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_myprofile_last_online_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='last_online_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
