# Generated by Django 4.1.7 on 2023-04-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_addfuturetravel_money_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfuturetravel',
            name='money_spent',
            field=models.CharField(choices=[(150, '150'), (225, '150-300'), (400, '300-500'), (750, '500-1000'), (2000, '1000-3000'), (3500, '3000+')], max_length=100),
        ),
        migrations.AlterField(
            model_name='addpasttravel',
            name='money_spent',
            field=models.CharField(choices=[(150, '150'), (225, '150-300'), (400, '300-500'), (750, '500-1000'), (2000, '1000-3000'), (3500, '3000+')], max_length=100),
        ),
    ]
