# Generated by Django 4.1.1 on 2022-12-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_remove_myprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofile',
            old_name='myuser',
            new_name='user',
        ),
    ]
